import { Routes } from '@angular/router';
import { ApiEndpoints } from '@core/api/api-endpoints';
import { FeaturePage } from '@shared/pages/feature-page/feature-page';

export const NOTIFICATION_ROUTES: Routes = [
  { path: '', component: FeaturePage, data: { title: 'Notifications', subtitle: 'In-app notifications for request stage transitions and pending actions.', mockKey: 'notifications', primaryAction: 'Mark All Read', capabilities: ['New submissions notify Endorsers.', 'Endorsed requests notify Approvers.', 'Returned, rejected, approved, and closed statuses notify Requesters.', 'Daily digest can be generated by backend job for stale approvals.'], endpoints: [ApiEndpoints.notifications.list, ApiEndpoints.notifications.unreadCount, ApiEndpoints.notifications.markRead(':id')] } }
];
